### ISSUE TITLE
iCloud Registration

### ISSUE THREAD

**Issue by HeavenlyBlow** [zipippino/HighSierraAspire5750G#1]
Hello. I have a problem registering iCloud. The service displays an error about exceeding the registration for this device, but I changed all the necessary data such as s/n, rom, mlb, uuid in different ways. I'm already desperate to find solutions. Can you help me?
My laptop is acer 5750G, i3, 8gb ram, high sierra

**Comment by frbuccoliero** [comment]
I'm sorry, this repo is discontinued.
